name: "Deploy GCP Function"

on:
  push:
    branches:
    - 'main'
    paths:
    - 'scheduler/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: CleverApp_Scheduler
          runtime: python38
          credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          entry_point: main
          source_dir: scheduler
          env_vars: SQL_USER=${{ secrets.SQL_USER }},SQL_PASSWORD=${{ secrets.SQL_PASSWORD }},SQL_HOST=${{ secrets.SQL_HOST }},SQL_DATABASE=${{ secrets.SQL_DATABASE }},GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},GCP_LOCATION=${{ secrets.GCP_LOCATION }},GCP_CLOUD_SCHEDULER=${{ secrets.GCP_CLOUD_SCHEDULER }}
