name: "Build and Test"

on:
  push:
    branches:
    - 'main'
    paths:
    - 'function/**'

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo Hello world